/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.view;

import com.hms.controller.PathologicalTestController;
import com.hms.controller.RadiologicalTestController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SIMEC IT INSTITUTE
 */
public class TestOutput extends javax.swing.JFrame {
  
    /**
     * Creates new form TestOutput
     */
//    public void showDetails(){
//        PathologicalTestController pTest = new PathologicalTestController();
//        Output.setText(pTest.returnRTestInfo());
//    }
    private String output;
    public TestOutput() {
        initComponents();
        populateTable();
//        PathologicalTestController pTest = new PathologicalTestController();
//        detailsBox.setText(pTest.returnRTestInfo());
//        DefaultTableModel tableModel = (DefaultTableModel)outputTable.getModel();
//        tableModel.addRow(pTest.returnRTestInfo());
//        model.addRow(pTest.arrayOfObjects().toArray());
//        jTable1.setModel(model);
    }
    
    public String outputResult(){
  
        PathologicalTestController pTest = new PathologicalTestController();
        RadiologicalTestController rTest = new RadiologicalTestController();
        
        try {
            if ((pTest.returnPTestInfo() != null) && (rTest.returnRTestInfo() == null)) {
                output = pTest.returnPTestInfo();
            }
            else if ((rTest.returnRTestInfo() != null) && (pTest.returnPTestInfo() == null)) {
                output = rTest.returnRTestInfo();
            }
        } catch (Exception e) {
        }
        return output;
    }
    public void populateTable(){
        PathologicalTestController pTest = new PathologicalTestController();
//       detailsBox.setText(pTest.returnRTestInfo());
        DefaultTableModel tableModel = (DefaultTableModel)outputTable.getModel();
       
        Object[] rowData = pTest.returnPTestInfo().split("\r\n");
//       Object[] rowData = pTest.arrayOfObjects().toArray();
        tableModel.addRow(rowData);
       
//       for(int index = 0; index<pTest.arrayOfObjects().size();index++){
//           rowData[0] = pTest.arrayOfObjects().get(index);
//           rowData[1] = pTest.arrayOfObjects().get(index);
//           rowData[2] = pTest.arrayOfObjects().get(index);
//           rowData[3] = pTest.arrayOfObjects().get(index);
//           tableModel.addRow(rowData);
//       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Output = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Output.setText("Details of Query");

        outputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Cost", "Availability", "Extra"
            }
        ));
        jScrollPane2.setViewportView(outputTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Output)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Output))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TestOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TestOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TestOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TestOutput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TestOutput().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Output;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable outputTable;
    // End of variables declaration//GEN-END:variables
}
